[build]
  command = '''
  printf "DIVIT_PLAST_SUPABASE_URL=%s\nDIVIT_PLAST_SUPABASE_ANON_KEY=%s\nDIVIT_PLAST_LLP_SUPABASE_URL=%s\nDIVIT_PLAST_LLP_SUPABASE_ANON_KEY=%s\n" "$DIVIT_PLAST_SUPABASE_URL" "$DIVIT_PLAST_SUPABASE_ANON_KEY" "$DIVIT_PLAST_LLP_SUPABASE_URL" "$DIVIT_PLAST_LLP_SUPABASE_ANON_KEY" > .env
  flutter build web --release
  '''
  publish = "build/web"

[[plugins]]
  package = "netlify-plugin-flutter"

  [plugins.inputs]
    channel = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200