// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpxwKPUys2lhvTh97KMIsEzVhoXuh8yM',
    appId: '1:14579148353:web:e434a2de03e5ea110bc8c0',
    messagingSenderId: '14579148353',
    projectId: 'divit-plast',
    authDomain: 'divit-plast.firebaseapp.com',
    storageBucket: 'divit-plast.firebasestorage.app',
    measurementId: 'G-70TYK31CR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcU55EG3n_Ze24e8Yu1MwKPAaNr16Vxfg',
    appId: '1:14579148353:android:a572542cebd87e4a0bc8c0',
    messagingSenderId: '14579148353',
    projectId: 'divit-plast',
    storageBucket: 'divit-plast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCgJ7ycO7XGkEOMWZ5YhVJ2K4DccplFps',
    appId: '1:14579148353:ios:9c32f0ac108773340bc8c0',
    messagingSenderId: '14579148353',
    projectId: 'divit-plast',
    storageBucket: 'divit-plast.firebasestorage.app',
    iosBundleId: 'com.example.manufacturingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCgJ7ycO7XGkEOMWZ5YhVJ2K4DccplFps',
    appId: '1:14579148353:ios:9c32f0ac108773340bc8c0',
    messagingSenderId: '14579148353',
    projectId: 'divit-plast',
    storageBucket: 'divit-plast.firebasestorage.app',
    iosBundleId: 'com.example.manufacturingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhpxwKPUys2lhvTh97KMIsEzVhoXuh8yM',
    appId: '1:14579148353:web:a9d5f535955cf7ef0bc8c0',
    messagingSenderId: '14579148353',
    projectId: 'divit-plast',
    authDomain: 'divit-plast.firebaseapp.com',
    storageBucket: 'divit-plast.firebasestorage.app',
    measurementId: 'G-GG9T5C408S',
  );
}
